import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define available languages
export type Language = 'fr' | 'en' | 'es';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations for each language
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Common elements
    "common.loading": "Chargement...",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.view": "Voir",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.noResults": "Aucun résultat trouvé",
    "common.tryAgain": "Essayez à nouveau",
    "common.continue": "Continuer",
    "common.back": "Retour",
    "common.send": "Envoyer",
    "common.yes": "Oui",
    "common.no": "Non",
    
    // Nav and footer
    "nav.home": "Accueil",
    "nav.profile": "Profil",
    "nav.appointments": "Rendez-vous",
    "nav.messaging": "Messagerie",
    "nav.map": "Carte",
    "nav.products": "Produits",
    "nav.tutorials": "Tutoriels",
    "nav.login": "Connexion",
    "nav.register": "Inscription",
    "nav.logout": "Déconnexion",
    "nav.findProfessional": "Trouver un professionnel",
    "nav.onlinePharmacy": "Pharmacie en ligne",
    "footer.quickLinks": "Liens rapides",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés",
    "footer.description": "Votre plateforme de santé connectée pour prendre soin de vous et de vos proches.",
    
    // Map page
    "map.title": "Trouvez des établissements de santé à proximité",
    "map.pharmacies": "Pharmacies",
    "map.healthCenters": "Centres de santé",
    "map.healthFacilities": "Trouver des établissements de santé",
    "map.facilitiesPlaceholder": "Rechercher un établissement de santé...",
    "map.locateMe": "Ma position",
    "map.sort.distance": "Distance",
    "map.sort.rating": "Évaluation",
    "map.sort.alphabetical": "Alphabétique",
    "map.filters.insurance": "Filtrer par assurance",
    "map.filters.yourInsurance": "Votre assurance",
    "map.filters.allInsurances": "Toutes les assurances",
    "map.locationEnabled": "Localisation activée",
    "map.locationEnabledMessage": "Les établissements sont maintenant triés par proximité.",
    "map.locationError": "Localisation non disponible",
    "map.locationErrorMessage": "Impossible d'accéder à votre position. Vérifiez vos paramètres de confidentialité.",
    "map.showMap": "Afficher la carte interactive",
    "map.loadingPlaces": "Chargement des établissements...",
    "map.noPlacesInsurance": "Aucun établissement trouvé pour \"{0}\" acceptant l'assurance {1}",
    "map.noPlaces": "Aucun établissement trouvé pour \"{0}\"",
    "map.viewOnMap": "Voir sur la carte",
    "map.distance": "Distance",
    "map.loadingMap": "Chargement de la carte...",
    "map.yourPosition": "Votre position",
    "map.insuranceAccepted": "Assurances acceptées",
    "map.updatingLocation": "Mise à jour de la position",
    "map.findingYourLocation": "Recherche de votre position en cours...",
    
    // Professionals page
    "professionals.title": "Professionnels de santé",
    "professionals.subtitle": "Trouvez et contactez les professionnels de santé dont vous avez besoin",
    "professionals.search.placeholder": "Rechercher par nom, spécialité ou lieu...",
    "professionals.filters.specialties": "Spécialités",
    "professionals.filters.consultationTypes": "Types de consultation",
    "professionals.filters.languages": "Langues parlées",
    "professionals.filters.inPerson": "Présentiel",
    "professionals.filters.video": "Vidéo",
    "professionals.filters.phone": "Téléphone",
    "professionals.contact": "Contacter",
    "professionals.appointment": "Prendre rendez-vous",
    "professionals.videoConsultation": "Consultation vidéo",
    "professionals.noResults": "Aucun professionnel ne correspond à votre recherche.",
    "professionals.tryAgain": "Essayez de modifier vos critères.",
    "professionals.specialty": "Spécialité",
    "professionals.location": "Lieu",
    
    // Medical Record page
    "medical.title": "Dossier médical",
    "medical.bloodType": "Groupe sanguin",
    "medical.history": "Antécédents médicaux",
    "medical.medications": "Médicaments actuels",
    "medical.allergies": "Allergies connues",
    "medical.vaccinations": "Vaccinations",
    "medical.emergency": "Contact d'urgence",
    "medical.share": "Partage sécurisé",
    "medical.addVaccination": "Ajouter une vaccination",
    "medical.editVaccination": "Modifier la vaccination",
    "medical.noVaccinations": "Aucune vaccination enregistrée",
    "medical.vaccineName": "Nom du vaccin",
    "medical.vaccineDate": "Date de vaccination",
    "medical.vaccineExpiry": "Date d'expiration",
    "medical.vaccineProvider": "Prestataire",
    "medical.vaccineBatch": "Numéro de lot",
    "medical.vaccineNotes": "Notes",
    "medical.emergencyContact": "Contact d'urgence",
    "medical.contactName": "Nom et prénom",
    "medical.contactRelationship": "Relation",
    "medical.contactPhone": "Téléphone",
    "medical.contactEmail": "Email",
    "medical.shareSecure": "Partage sécurisé du dossier",
    "medical.shareDescription": "Partagez votre dossier médical de manière sécurisée avec un professionnel de santé via un QR code ou un lien temporaire.",
    "medical.shareGenerate": "Générer le partage",
    
    // Profile page and preferences
    "profile.title": "Profil",
    "profile.personalInfo": "Informations personnelles",
    "profile.medicalInfo": "Informations médicales",
    "profile.insurance": "Assurance",
    "profile.preferences": "Préférences",
    "profile.prescriptions": "Ordonnances",
    "profile.save": "Enregistrer les modifications",
    "preferences.title": "Préférences",
    "preferences.language": "Langue",
    "preferences.notifications": "Notifications",
    "preferences.privacy": "Confidentialité",
    "preferences.notifEmail": "Recevoir des emails pour les rappels de rendez-vous",
    "preferences.notifSms": "Recevoir des SMS pour les rappels de rendez-vous",
    "preferences.reminderFreq": "Fréquence des rappels",
    "preferences.reminderDaily": "Quotidien",
    "preferences.reminder3Days": "3 jours avant",
    "preferences.reminderWeekly": "Hebdomadaire",
    "preferences.privacyTitle": "Confidentialité",
    "preferences.privacyInfo": "Ces paramètres déterminent comment vos informations médicales sont partagées avec les professionnels de santé.",
    "preferences.shareProfile": "Autoriser l'accès à mon profil pour mes professionnels de santé",
    "preferences.shareData": "Partager mes données anonymisées pour améliorer la plateforme",
    "preferences.saveButton": "Enregistrer les préférences",
    "preferences.updatedSuccess": "Préférences mises à jour",
    "preferences.updatedDescription": "Vos préférences ont été enregistrées avec succès.",
    
    // Currency related
    "currency.format": "{0} F CFA",
  },
  en: {
    // Common elements
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.noResults": "No results found",
    "common.tryAgain": "Try again",
    "common.continue": "Continue",
    "common.back": "Back",
    "common.send": "Send",
    "common.yes": "Yes",
    "common.no": "No",
    
    // Nav and footer
    "nav.home": "Home",
    "nav.profile": "Profile",
    "nav.appointments": "Appointments",
    "nav.messaging": "Messaging",
    "nav.map": "Map",
    "nav.products": "Products",
    "nav.tutorials": "Tutorials",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.logout": "Logout",
    "nav.findProfessional": "Find a professional",
    "nav.onlinePharmacy": "Online pharmacy",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved",
    "footer.description": "Your connected health platform for taking care of you and your loved ones.",
    
    // Map page
    "map.title": "Find healthcare facilities nearby",
    "map.pharmacies": "Pharmacies",
    "map.healthCenters": "Health Centers",
    "map.healthFacilities": "Find healthcare facilities",
    "map.facilitiesPlaceholder": "Search for a healthcare facility...",
    "map.locateMe": "My location",
    "map.sort.distance": "Distance",
    "map.sort.rating": "Rating",
    "map.sort.alphabetical": "Alphabetical",
    "map.filters.insurance": "Filter by insurance",
    "map.filters.yourInsurance": "Your insurance",
    "map.filters.allInsurances": "All insurances",
    "map.locationEnabled": "Location enabled",
    "map.locationEnabledMessage": "Facilities are now sorted by proximity.",
    "map.locationError": "Location unavailable",
    "map.locationErrorMessage": "Unable to access your location. Check your privacy settings.",
    "map.showMap": "Show interactive map",
    "map.loadingPlaces": "Loading facilities...",
    "map.noPlacesInsurance": "No facilities found for \"{0}\" accepting insurance {1}",
    "map.noPlaces": "No facilities found for \"{0}\"",
    "map.viewOnMap": "View on map",
    "map.distance": "Distance",
    "map.loadingMap": "Loading map...",
    "map.yourPosition": "Your position",
    "map.insuranceAccepted": "Accepted insurances",
    "map.updatingLocation": "Updating location",
    "map.findingYourLocation": "Finding your location...",
    
    // Professionals page
    "professionals.title": "Healthcare Professionals",
    "professionals.subtitle": "Find and contact the healthcare professionals you need",
    "professionals.search.placeholder": "Search by name, specialty or location...",
    "professionals.filters.specialties": "Specialties",
    "professionals.filters.consultationTypes": "Consultation Types",
    "professionals.filters.languages": "Spoken Languages",
    "professionals.filters.inPerson": "In Person",
    "professionals.filters.video": "Video",
    "professionals.filters.phone": "Phone",
    "professionals.contact": "Contact",
    "professionals.appointment": "Make appointment",
    "professionals.videoConsultation": "Video consultation",
    "professionals.noResults": "No professionals match your search.",
    "professionals.tryAgain": "Try modifying your criteria.",
    "professionals.specialty": "Specialty",
    "professionals.location": "Location",
    
    // Medical Record page
    "medical.title": "Medical Record",
    "medical.bloodType": "Blood Type",
    "medical.history": "Medical History",
    "medical.medications": "Current Medications",
    "medical.allergies": "Known Allergies",
    "medical.vaccinations": "Vaccinations",
    "medical.emergency": "Emergency Contact",
    "medical.share": "Secure Sharing",
    "medical.addVaccination": "Add vaccination",
    "medical.editVaccination": "Edit vaccination",
    "medical.noVaccinations": "No vaccinations recorded",
    "medical.vaccineName": "Vaccine name",
    "medical.vaccineDate": "Vaccination date",
    "medical.vaccineExpiry": "Expiry date",
    "medical.vaccineProvider": "Provider",
    "medical.vaccineBatch": "Batch number",
    "medical.vaccineNotes": "Notes",
    "medical.emergencyContact": "Emergency Contact",
    "medical.contactName": "Full name",
    "medical.contactRelationship": "Relationship",
    "medical.contactPhone": "Phone",
    "medical.contactEmail": "Email",
    "medical.shareSecure": "Secure Medical Record Sharing",
    "medical.shareDescription": "Share your medical record securely with a healthcare professional via QR code or temporary link.",
    "medical.shareGenerate": "Generate sharing",
    
    // Profile page and preferences
    "profile.title": "Profile",
    "profile.personalInfo": "Personal Information",
    "profile.medicalInfo": "Medical Information",
    "profile.insurance": "Insurance",
    "profile.preferences": "Preferences",
    "profile.prescriptions": "Prescriptions",
    "profile.save": "Save changes",
    "preferences.title": "Preferences",
    "preferences.language": "Language",
    "preferences.notifications": "Notifications",
    "preferences.privacy": "Privacy",
    "preferences.notifEmail": "Receive emails for appointment reminders",
    "preferences.notifSms": "Receive SMS for appointment reminders",
    "preferences.reminderFreq": "Reminder frequency",
    "preferences.reminderDaily": "Daily",
    "preferences.reminder3Days": "3 days before",
    "preferences.reminderWeekly": "Weekly",
    "preferences.privacyTitle": "Privacy",
    "preferences.privacyInfo": "These settings determine how your medical information is shared with healthcare professionals.",
    "preferences.shareProfile": "Allow access to my profile for my healthcare professionals",
    "preferences.shareData": "Share my anonymized data to improve the platform",
    "preferences.saveButton": "Save preferences",
    "preferences.updatedSuccess": "Preferences updated",
    "preferences.updatedDescription": "Your preferences have been successfully saved.",
    
    // Currency related
    "currency.format": "{0} CFA francs",
  },
  es: {
    // Common elements
    "common.loading": "Cargando...",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.view": "Ver",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.noResults": "No se encontraron resultados",
    "common.tryAgain": "Intentar de nuevo",
    "common.continue": "Continuar",
    "common.back": "Volver",
    "common.send": "Enviar",
    "common.yes": "Sí",
    "common.no": "No",
    
    // Nav and footer
    "nav.home": "Inicio",
    "nav.profile": "Perfil",
    "nav.appointments": "Citas",
    "nav.messaging": "Mensajería",
    "nav.map": "Mapa",
    "nav.products": "Productos",
    "nav.tutorials": "Tutoriales",
    "nav.login": "Iniciar sesión",
    "nav.register": "Registrarse",
    "nav.logout": "Cerrar sesión",
    "nav.findProfessional": "Encontrar un profesional",
    "nav.onlinePharmacy": "Farmacia en línea",
    "footer.quickLinks": "Enlaces rápidos",
    "footer.contact": "Contacto",
    "footer.rights": "Todos los derechos reservados",
    "footer.description": "Tu plataforma de salud conectada para cuidar de ti y de tus seres queridos.",
    
    // Map page
    "map.title": "Encuentra establecimientos de salud cercanos",
    "map.pharmacies": "Farmacias",
    "map.healthCenters": "Centros de salud",
    "map.healthFacilities": "Encontrar centros de salud",
    "map.facilitiesPlaceholder": "Buscar un centro de salud...",
    "map.locateMe": "Mi ubicación",
    "map.sort.distance": "Distancia",
    "map.sort.rating": "Valoración",
    "map.sort.alphabetical": "Alfabético",
    "map.filters.insurance": "Filtrar por seguro",
    "map.filters.yourInsurance": "Tu seguro",
    "map.filters.allInsurances": "Todos los seguros",
    "map.locationEnabled": "Ubicación activada",
    "map.locationEnabledMessage": "Los establecimientos ahora están ordenados por proximidad.",
    "map.locationError": "Ubicación no disponible",
    "map.locationErrorMessage": "No se puede acceder a tu ubicación. Verifica tu configuración de privacidad.",
    "map.showMap": "Mostrar mapa interactivo",
    "map.loadingPlaces": "Cargando establecimientos...",
    "map.noPlacesInsurance": "No se encontraron establecimientos para \"{0}\" que acepten el seguro {1}",
    "map.noPlaces": "No se encontraron establecimientos para \"{0}\"",
    "map.viewOnMap": "Ver en el mapa",
    "map.distance": "Distancia",
    "map.loadingMap": "Cargando mapa...",
    "map.yourPosition": "Tu posición",
    "map.insuranceAccepted": "Seguros aceptados",
    "map.updatingLocation": "Actualizando ubicación",
    "map.findingYourLocation": "Buscando tu ubicación...",
    
    // Professionals page
    "professionals.title": "Profesionales de la salud",
    "professionals.subtitle": "Encuentra y contacta con los profesionales de la salud que necesitas",
    "professionals.search.placeholder": "Buscar por nombre, especialidad o ubicación...",
    "professionals.filters.specialties": "Especialidades",
    "professionals.filters.consultationTypes": "Tipos de consulta",
    "professionals.filters.languages": "Idiomas hablados",
    "professionals.filters.inPerson": "Presencial",
    "professionals.filters.video": "Vídeo",
    "professionals.filters.phone": "Teléfono",
    "professionals.contact": "Contactar",
    "professionals.appointment": "Pedir cita",
    "professionals.videoConsultation": "Consulta por vídeo",
    "professionals.noResults": "Ningún profesional coincide con tu búsqueda.",
    "professionals.tryAgain": "Intenta modificar tus criterios.",
    "professionals.specialty": "Especialidad",
    "professionals.location": "Ubicación",
    
    // Medical Record page
    "medical.title": "Historial médico",
    "medical.bloodType": "Grupo sanguíneo",
    "medical.history": "Historial médico",
    "medical.medications": "Medicamentos actuales",
    "medical.allergies": "Alergias conocidas",
    "medical.vaccinations": "Vacunas",
    "medical.emergency": "Contacto de emergencia",
    "medical.share": "Compartir seguro",
    "medical.addVaccination": "Añadir vacuna",
    "medical.editVaccination": "Editar vacuna",
    "medical.noVaccinations": "No hay vacunas registradas",
    "medical.vaccineName": "Nombre de la vacuna",
    "medical.vaccineDate": "Fecha de vacunación",
    "medical.vaccineExpiry": "Fecha de caducidad",
    "medical.vaccineProvider": "Proveedor",
    "medical.vaccineBatch": "Número de lote",
    "medical.vaccineNotes": "Notas",
    "medical.emergencyContact": "Contacto de emergencia",
    "medical.contactName": "Nombre completo",
    "medical.contactRelationship": "Relación",
    "medical.contactPhone": "Teléfono",
    "medical.contactEmail": "Correo electrónico",
    "medical.shareSecure": "Compartir historial médico de forma segura",
    "medical.shareDescription": "Comparte tu historial médico de forma segura con un profesional de la salud mediante código QR o enlace temporal.",
    "medical.shareGenerate": "Generar compartición",
    
    // Profile page and preferences
    "profile.title": "Perfil",
    "profile.personalInfo": "Información personal",
    "profile.medicalInfo": "Información médica",
    "profile.insurance": "Seguro",
    "profile.preferences": "Preferencias",
    "profile.prescriptions": "Recetas",
    "profile.save": "Guardar cambios",
    "preferences.title": "Preferencias",
    "preferences.language": "Idioma",
    "preferences.notifications": "Notificaciones",
    "preferences.privacy": "Privacidad",
    "preferences.notifEmail": "Recibir correos electrónicos para recordatorios de citas",
    "preferences.notifSms": "Recibir SMS para recordatorios de citas",
    "preferences.reminderFreq": "Frecuencia de recordatorios",
    "preferences.reminderDaily": "Diario",
    "preferences.reminder3Days": "3 días antes",
    "preferences.reminderWeekly": "Semanal",
    "preferences.privacyTitle": "Privacidad",
    "preferences.privacyInfo": "Estos ajustes determinan cómo se comparte tu información médica con los profesionales de la salud.",
    "preferences.shareProfile": "Permitir el acceso a mi perfil para mis profesionales de la salud",
    "preferences.shareData": "Compartir mis datos anonimizados para mejorar la plataforma",
    "preferences.saveButton": "Guardar preferencias",
    "preferences.updatedSuccess": "Preferencias actualizadas",
    "preferences.updatedDescription": "Tus preferencias se han guardado correctamente.",
    
    // Currency related
    "currency.format": "{0} francos CFA",
  }
};

// Provider component
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');
  
  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook to use the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
