// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvhcsgojkobqpkpxixnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aGNzZ29qa29icXBrcHhpeG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjI3MTEsImV4cCI6MjA1OTM5ODcxMX0.mju077yLTBEzD3d0b6tLPqHtKTQYhlTq67r8RVtk0ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);